### ISSUE TITLE
Add support for other glsl shader types

### ISSUE THREAD

**Issue by ghost** [euler0/sublime-glsl#17]
These are `.mesh` `.task`, `.rgen`, `.rint`, `.rahit`, `.rchit`, `rmiss`, and `rcall`

**Comment by rwols** [comment]
Would adding these file extensions to this list resolve your problem?

https://github.com/euler0/sublime-glsl/blob/4cd4acfffc7f2ab4f154b6ebfbbe0bb71825eb89/GLSL.sublime-syntax#L6

**Comment by EnterpriseToast** [comment]
Yes

**Comment by euler0** [comment]
I’ve published a new version to add these new extensions.

Thanks @EnterpriseToast, and Raoul(@rwols), too!
