### ISSUE TITLE
no color this picture

### ISSUE THREAD

**Issue by yingnierxiao** [euler0/sublime-glsl#7]
![99eafa70-dfbc-4962-b2bf-51af1435aee9](https://cloud.githubusercontent.com/assets/3435706/15601153/b1cee61c-2420-11e6-80c8-54430f11bede.png)

**Comment by euler0** [comment]
I've just identified the issue. Thank you for the reporting this issue, @yingnierxiao

**Comment by euler0** [comment]
Fixed. New version will be delivered soon!
